spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.datasource:
  driver_class_name: com.mysql.cj.jdbc.Driver
  url: "jdbc:mysql://localhost:3306/usedCarsDatabase"
  username: "_test"
  password: "_test"
