spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create
spring.datasource:
  driver_class_name: com.mysql.cj.jdbc.Driver
  url: "jdbc:mysql://localhost:3306/usedCarsDatabase"
  username: "user"
  password: "localhost1234"
