#itt lehet beallitani hogy jdbc vagy mem legyen az ahonnan elérjük és tároljuk az adatokat
daoType: jdbc
jdbcUser: user
jdbcPassword: localhost1234
jdbcDatabase: usedCarsDatabase
jdbcUrl: localhost:3306
jdbcPoolSize: 10

